name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16.13.0"

      - name: Install dépendance for node.js
        run: npm install

      - name: Install dépendance and build react interface
        run: |
          cd client
          npm install
          npm run build

      - name: Run Test
        run: npm test